version: '3.5'

services:
    nginx-service:
        container_name: ${COMPOSE_PROJECT_NAME:-nginx}_server
        build:
            context: ./docker/nginx
        image: nginx:${NGINX_VERSION:-latest}
        ports:
            - ${NGINX_PORT:-8001}:80
        volumes:
            - ${ENVIRONMENT}/${PROJECT_DIR}/${APP_DIR}:/home/phpuser/appdata/
            - ${ENVIRONMENT}/${PROJECT_DIR}/docker/nginx:/etc/nginx/conf.d
        networks:
            - php-network
        depends_on:
            - php-be

    php-be:
        container_name: ${COMPOSE_PROJECT_NAME:-php}_service
        build:
            context: ./docker/php
        image: php:${PHP_VERSION}
        environment:
            PHP_IDE_CONFIG: serverName=Docker
        volumes:
            - ${ENVIRONMENT}/${PROJECT_DIR}/${APP_DIR}:/home/phpuser/appdata/
            - ${ENVIRONMENT}/${PROJECT_DIR}/docker/php:/usr/local/etc/php/
            - ~/.ssh/id_rsa:/home/phpuser/.ssh/id_rsa
        networks:
            - php-network
        depends_on:
            - php-db

    php-db:
        container_name: ${COMPOSE_PROJECT_NAME:-mariadb}_database
        image: ${DB_VERSION:-mariadb:10.3.9}
        ports:
            - ${DATABASE_PORT:-3306}:3306
        environment:
            MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME:-php}_database
            MYSQL_USER: ${DATABASE_USER:-user}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD:-password}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root}
        command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
        volumes:
            - ${DATABASE_DIR}:/var/lib/mysql
        networks:
            - php-network

volumes:
    php-db:

networks:
    php-network:
        external: true
